### ISSUE TITLE
Biohansel does not recognize collections of SPAdes assemblies without .fasta extension

### ISSUE THREAD

**Issue by glabbe** [phac-nml/galaxy_tools#148]
We tried to assemble a collection of .fastq WGS datasets with SPAdes, and tried to run Biohansel on the dataset list in Galaxy, and got an error.  Biohansel does not see any input files.n  Perhaps the wrapper needs to be fixed.  @apetkau @DarianHole

**Comment by DarianHole** [comment]
Hi @glabbe 

I've tested this on my local galaxy and it seems that biohansel is not detecting the spades assembly as an input.

![error_issue148](https://user-images.githubusercontent.com/46600008/61561403-85b89a80-aa34-11e9-8bd8-7526da8ca162.png)

I'm not sure why this is happening but I'll play around with it to see if I can find any more information

**Comment by glabbe** [comment]
@DarianHole yes we found that if we change the file name of the SPAdes assembly by adding ".fasta" to it, then BioHansel can detect it.  I think that we need to change the wrapper so that in galaxy, the lists of assemblies in .fasta format can be used as input without the ".fatsa" extension.

**Comment by DarianHole** [comment]
Should be fixed in #149, if not reopen this and I'll look for another solution
