### ISSUE TITLE
Assemblystats fails in latest version of Galaxy release (20.01)

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/galaxy_tools#190]
Default Galaxy version default python version is now 3.X where it was 2.7.X . Tools needs to be updated

**Comment by Takadonet** [comment]
stacktrace

>  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/nml/assemblystats/ad2b274663f8/assemblystats/assembly_stats_txt.py", line 39
>     except Exception, e:
>                     ^
> SyntaxError: invalid syntax

**Comment by hellothisisMatt** [comment]
Addressed in #193, updated to be python 3 compatible.
