### ISSUE TITLE
Assemblystats gnuplot failed conda

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/galaxy_tools#191]
So just re-installed gnuplot=5.0.4 on our Centos 7 machines and looks like one of the dependencies for gnuplot got upgraded (libwebp) from libwebp.so.6 to libwebp.so.7 . Getting following stacktrace from tool.

gnuplot: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory

> ** WARNING: GNUplot pipe returned non-zero status: '32512'
> 
> 
> ** ERROR: Failed to create /Galaxy/jobs/005/496/5496674/working/dataset_1_files/histogram_bins.dat.png'**

Upgrade gnuplot to latest version and see if it fixes issue and still works with Assemblystats.

**Comment by hellothisisMatt** [comment]
Fixed in #193
