### ISSUE TITLE
Update bio_hansel galaxy wrapper with Galaxy 17.09 & Conda 3

### ISSUE THREAD

**Issue by hellothisisMatt** [phac-nml/galaxy_tools#57]
During testing of bio_hansel's wrapper, we discovered that bio_hansel will fail travis CI testing without `attrs` listed in the requirements. This shouldn't be necessary as the recipe installs `attrs` anyways. We found this is an issue with the older versions of Galaxy and Conda. When Galaxy is updated to version 17.09, and Conda is updated to version 3.x.x 
Refer to https://github.com/phac-nml/galaxy_tools/pull/54/commits/753a2903099cd517fe26b02951fad9c6955d7a0d, on the required work.

**Comment by Takadonet** [comment]
Been addressed.
