### ISSUE TITLE
assembly_stats_txt.py does not return error code

### ISSUE THREAD

**Issue by peterjc** [phac-nml/galaxy_tools#93]
Currently code is:

https://github.com/phac-nml/galaxy_tools/blob/master/tools/assemblystats/assembly_stats_txt.py#L18

```python
def stop_err(msg):
    sys.stderr.write('%s\n' % msg)
    sys.exit()
```

This will return a zero exit level, i.e. no error will be report by Galaxy.

Quick fix:

```python
def stop_err(msg):
    sys.stderr.write('%s\n' % msg)
    sys.exit(1)
```

Better fix, replace all calls to ``stop_err`` with ``sys.exit`` which will accept a string, print this to stderr, and exit with return code one.

**Comment by hellothisisMatt** [comment]
Addressed in #193 
Returns the actual exit code from the .pl script, and the output as well.
