### ISSUE TITLE
assembly_stats_txt.xml still at v1.0.1

### ISSUE THREAD

**Issue by peterjc** [phac-nml/galaxy_tools#94]
https://github.com/phac-nml/galaxy_tools/blob/master/tools/assemblystats/assembly_stats_txt.xml starts:

```xml
<tool id="assemblystats" name="assemblystats" version="1.0.1">
	<description>Summarise an assembly (e.g. N50 metrics)</description>
	<requirements>
...
```

This is the exact same version number as Konrad's original which is also still on the tool shed, which makes it very confusing as your version has a number of changes:

https://toolshed.g2.bx.psu.edu/view/nml/assemblystats/
https://toolshed.g2.bx.psu.edu/view/konradpaszkiewicz/assemblystats/

**Comment by hellothisisMatt** [comment]
Updated to 1.1.0 in PR #193
